sudo: required
dist: trusty
language: generic

compiler:
  - gcc

notifications:
  email:
    on_failure: always
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu USE_DEB=true NOT_TEST_INSTALL=true ABICHECK_URL='github:ros-perception/ar_track_alvar#indigo-devel'
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu USE_DEB=true NOT_TEST_INSTALL=true VERBOSE_OUTPUT='true'
    - ROS_DISTRO="indigo" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
